### ISSUE TITLE
Spanish translation website

### ISSUE THREAD

**Issue by Idrinth** [idrinth-api-bench/api-bench#207]
**Context**
- Language: Spanish
- Translator: no
- Project: Website

requires #147

**Comment by martincarapia** [comment]
Hey I can snag this. Although I speak Spanish from Mexico (LATAM), would that be a problem?

**Comment by Idrinth** [comment]
> Hey I can snag this. Although I speak Spanish from Mexico (LATAM), would that be a problem?

no  problem  at all :)  Thank  you!
