### ISSUE TITLE
first steps into automated testing: cypress & e2e

### ISSUE THREAD

**Issue by Idrinth** [idrinth-api-bench/api-bench#226]
**Context**
Currently cypress is doing some very basic tests for the website pages. It makes sure they are loaded, they are linked to where appropriate and they have the right title.

**Project**
File: /website/cypress/e2e

**Goal**
We need to be sure, that the copyright in the footer is correct. This means, that it starts in 2020 and is updated for the current year.

**Comment by MohamedSy1** [comment]
Yeah, I will work on this.
