### ISSUE TITLE
Add X/Twitter to website

### ISSUE THREAD

**Issue by Idrinth** [idrinth-api-bench/api-bench#667]
https://twitter.com/IdrinthApiBench

**Comment by simileoluwa** [comment]
Hi @Idrinth is this something i can look into if no one is assigned to it yet? Thanks

**Comment by Idrinth** [comment]
> Hi @Idrinth is this something i can look into if no one is assigned to it yet? Thanks

Great! Go right ahead!

**Comment by simileoluwa** [comment]
Thanks.

**Comment by simileoluwa** [comment]
where would you lime it to be added please?

**Comment by Idrinth** [comment]
> where would you like the X logo to be added please?

with all the other social icons in the header

**Comment by simileoluwa** [comment]
OK Great.

**Comment by hussainnaqvee** [comment]
I would like to take this issue.

**Comment by Idrinth** [comment]
> I would like to take this issue.

sure, thanks!
